### ISSUE TITLE
Possible support for Literals

### ISSUE THREAD

**Issue by vikigenius** [jnoortheen/arger#1]
Hi, thanks for this very nice library. It looks very good.

I have a suggestion. Would it be possible to support Literals: https://docs.python.org/3/library/typing.html#typing.Literal

Right now, we can use Enum to denote choices, which is good. But we can also use the new Literal typing to denote choices, which can be very convenient.

**Comment by jnoortheen** [comment]
Yes it is in my to-do list. I will update it soon.
