### ISSUE TITLE
Optional type annotation handled incorrectly

### ISSUE THREAD

**Issue by vikigenius** [jnoortheen/arger#2]
Try to run the example in
https://github.com/jnoortheen/arger/blob/1bb8b4ec7d6f4787d3fcb40f4423a0d2013ab518/docs/examples/3-arger-as-function/src.py

```
python src.py -o 'log.txt' list
```

This shows error:
```
pytest: error: argument -o/--log-file: invalid typing.Union value: 'log.txt'
```

**Comment by vikigenius** [comment]
Changing this line:

https://github.com/jnoortheen/arger/blob/8dc13c4450657ef4d38cae51e487b79508c8f803/arger/main.py#L388

to

```
if tp_utils.is_optional(typ) and "default" in kwargs:
```

Fixes the issue, what is the rationale behind it? Is it needed for some other case?

**Comment by jnoortheen** [comment]
using `nargs` means, it is supposed to be a argument without flag. In this case, log_file is an optional argument and should be converted to a flag(--logfile), so it checks for defaults. 

The case where it will work is 

```py
def list(cont: Optional[str]):
    ...
```
here it will print None if nothing comes after list or passes the value if given. 

The program should handle `Optional[str]=None` anyway. I will add a fix.
