### ISSUE TITLE
Handling docstrings when using Argument class

### ISSUE THREAD

**Issue by vikigenius** [jnoortheen/arger#3]
Say, I want to create a countable argument like this

```
Verbosity = Argument(type=int, action='count', default=0)

@Arger.init(prog='parse')
def arger(verbosity: int = Verbosity, config_path: Path = DEFAULT_CONFIG_PATH):
    """My Parser.

    Args:
        verbosity: Counted argument, use -v for info and -vv for debug.
        config_path: Path to config file.
    """
```

The help string for verboisty shows this

```
  -v VERBOSITY, --verbosity VERBOSITY
                        Counted argument, use -v for info and -vv for debug. (default: <Argument: (), {'default': 0, 'type': <class 'int'>, 'action':
                        'count'}>)
```

Can we modify the default value part of the help string to show as 0 instead of 
`(default: <Argument: (), {'default': 0, 'type': <class 'int'>, 'action':
                        'count'}>)`

**Comment by vikigenius** [comment]
The problem is python 3.8 does not have the Annotated type in the typing module.

**Comment by jnoortheen** [comment]
For typing you can use https://pypi.org/project/typing-extensions/#

The above example should be written as 

```py
Verbosity = Argument(action='count')

@Arger.init(prog='parse')
def arger(verbosity: int = Verbosity=0, config_path: Path = DEFAULT_CONFIG_PATH):
    """My Parser.

    Args:
        verbosity: Counted argument, use -v for info and -vv for debug.
        config_path: Path to config file.
    """
```

The default value should be defined in the function in order to make that parameter optional
